#!/bin/bash

# trying to load local .gitsa file if any exists
function gitsa() {
	localGITSA="`pwd`/.gitsa"
	# skip self-loop .gitsa re-include
	if [[ "$BASH_SOURCE" != "$localGITSA" ]]; then
	  if [[ -e $localGITSA ]]; then
	      source $localGITSA
	  else
	      echo -e "\e[33mNo local \`.gitsa\` file found!\e[m"
	  fi
	fi

	# promt the success
	echo -e "\e[32mThe Git Shortcut Aliases Are In Effect.\e[m"
}

# fixup a commit in the history, add/remove content/file from past commits
# ref: https://stackoverflow.com/a/27721031/1198291
function commit-fixup() {
	git commit --fixup=$1
	git rebase --interactive --autosquash $1^
}
